### ISSUE TITLE
Address lines maximum characters

### ISSUE THREAD

**Issue by NicoVanMoortel** [erasmus-without-paper/ewp-specs-types-address#1]
When an address is given using address lines, a maximum of 4 address lines is set. Should we also set a maximum amount of characters for each line? 
(fyi: in our system it is limited to 8 lines and maximum 50 characters in each line. This way the entire address is visible when printed and placed in an envelope with a standard window.)

**Comment by wrygiel** [comment]
I don't think there's any standard for this. This means that other systems might have 60 characters, while others would have 40. You must be prepared to receive any kind of input, and - possibly - split or join the lines appropriately.

https://github.com/erasmus-without-paper/ewp-specs-types-address/blob/d37ff45130753f3408f2f171fdd037cf4ce4bf96/schema.xsd#L77

**Comment by NicoVanMoortel** [comment]
I also think that there is no standard. 

I suppose that most client who work with non-structured addresses, will have a maximum set for each address line and maybe also for the total. If the xsd does not set a maximum, the client must be able to process an address which is longer than its internal maximum. Which will probably mean cutting the address.

If some restrictions are set, a client can decide to cut the addresses if it is bigger then it can handle or change in order to handle everything.

**Comment by wrygiel** [comment]
I have no strong opinions in this matter. Perhaps some other developers will? @erasmus-without-paper/all-members 

Regardless of what we choose, **clients** will need to do some splitting or concatenating if they want to import the address into their database.

It looks a bit differently for **servers** though. In the current solution, the servers don't need to either split nor concatenate, they just output. If a limit is present (e.g. 30 characters), then some servers will be required to split their data.

This is the only reason why I didn't set a limit here - to make server development easier. Since servers will be developed first (before the clients), this seemed a reasonable choice.

**Comment by huntering** [comment]
I agree with Nico that we should define a maximum nr of characters that is still acceptable for printing purposes.

**Comment by georgschermann** [comment]
some client systems of ours restrict it to 50 characters, in our database we don't restrict the length.
I am not sure if we should restrict the length for printing purposes in erasmus **without** paper :-)

**Comment by wrygiel** [comment]
It seems that OASIS is currently the only partner to request this.

**Comment by wrygiel** [comment]
Address datatype got approved to `stable-v1`, so I'm closing topics about backward-incompatible features.
