### ISSUE TITLE
Address lines mandatory fields

### ISSUE THREAD

**Issue by NicoVanMoortel** [erasmus-without-paper/ewp-specs-types-address#2]
Can it be made mandatory that an address always contains a country, postal code an locality? 

If we receive an address in a non structured form (address lines), we always require country, postal code an locality. This for reporting purposes. If the 3 attributes are mandatory, we would not need to manually extract this information from the address lines.

**Comment by wrygiel** [comment]
> we would not need to manually extract this information from the address lines

Note, that it is already [stated](https://github.com/erasmus-without-paper/ewp-specs-types-address/blob/d37ff45130753f3408f2f171fdd037cf4ce4bf96/schema.xsd#L72) that `addressLine`s SHOULD NOT contain values defined in `locality`, `postalCode`, `region` and `country`. (It's "SHOULD NOT", but not "MUST NOT".)

### Country and locality

As to making `country` and `locality` required: I agree that all valid addresses should have those fields present. I can see two solutions to your problem though:

* **Solution 1:** We can express in the documentation that these fields are "highly recommended", but abstain from strictly requiring them. If client implementations require them to be present, then such clients may ignore such addresses.

  However, I believe that even in such extreme cases (missing locality), you (or other clients) might still make some use of such an address. After all, you are not strictly required to store those addresses in your own database - often, you'll just need to display them (e.g. directly from the EWP response).

* **Solution 2:** Make them required. However, I can see some possible drawbacks of this approach. Let's assume that one of future EWP partners stores addresses in not-so-reasonable format - they chose to store the locality as part of the addressLine string, instead of having it in a separate field. (Seems unlikely, but still plausible.) If we make these elements required, such partner will be unable to share *any* addresses with EWP, which would be very bad.

### Postal code

According to many sources I have read, many countries still don't use postal codes. It is hard to believe for us in Europe, but it's pretty common in, say, Africa. And, if I understood correctly, there is talk of African countries joining the Erasmus Programme. This might mean that such (possibly valid) addresses might begin to pop up in places.

### My proposal

* I would choose **solution 1** described above - make all these elements **highly recommended**, but not "schema-required".
* 99.9% address will have those elements, but 0.1% might not. Clients MAY choose to **ignore** addresses without these "recommended" elements. **Just treat them as they would not exist.** This still leaves some room for the weird cases I have mentioned.

What do you think?

**Comment by wrygiel** [comment]
One more thing is worth pointing out: Street addresses (as opposed to postal addresses) are not required to have a postal code, because they don't serve "postal purpose" (their purpose is to find the person, office or institution). Currently we use `FlexibleAddress` to handle both street addresses and postal addresses.

**Comment by NicoVanMoortel** [comment]
Postal codes from African countries have indeed given us some problems. In these cases dummy postal codes were created (by us or by the student who is also required to give a postal code). This is not the cleanest solution, but if an address is not partially structured, we have no use for it. 

One of the main reasons is reporting. “provide a list of all students from country A or from locality B”. 

I understand the choice for solution 1 (and we would indeed ignore the non-structured addresses). Some partners might have problems with extra restrictions. But if there are no restrictions, only recommendations, there is no control on the quality of the data.  

If like you said only 0,1% of the addresses have no postal code, why not make it mandatory? A partner can decide not to send the address or to ‘work around’ the restriction (which the client cannot do in an automated process). This way the client is sure of the quality of the address it receives.

**Comment by wrygiel** [comment]
> If like you said only 0,1% of the addresses have no postal code, why not make it mandatory?

Because we don't want to force anyone to submit dummy/fake postal codes. As you have admitted above, that would not be a clean solution.

> But if there are no restrictions, only recommendations, there is no control on the quality of the data.

Excessive restrictions *also* can lead to a loss in quality of data (because people are forced to submit invalid values, simply to meet such unfair restrictions).

**Comment by wrygiel** [comment]
Address datatype got approved to `stable-v1`, so I'm closing topics about backward-incompatible features.
